when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    repo: Moria/Gimli
  - event: pull_request

steps:
  - name: build
    image: gradle:8.6-jdk17
    commands:
      - ./gradlew build
  - name: release
    image: gradle:8.6-jdk17
    when:
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
        repo: Moria/Gimli
    commands:
      - ./gradlew publish
    secrets: [ codeberg_create_packages_token ]